### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by leouebe95** [nacholibre/node-readlines#14]
I converted scripts from another language to NodeJS, and ran into performance issues: The NodeJS version was running 2 to 3 times slower than previous scripts. I tracked it down to the LineByLine.prototype._extractLines method.

Changing the while loop and bufferPosition++ to use directly buffer.indexOf solved the issue. I can provide the code snippet if needed. 

Please fix this performance issue in the next release.

**Comment by nacholibre** [comment]
Can you post the fixed code?

**Comment by leouebe95** [comment]
here is the version that I use now. I changed only  _extractLines. 

LineByLine.prototype._extractLines = function(buffer) {
    var line;
    var lines = [];
    var lastNewLine = 0;
    while (true) {
        var nextPos = buffer.indexOf(this.newLineCharacter, lastNewLine)+1;
        if (nextPos > 0) {
            line = buffer.slice(lastNewLine, nextPos);
            lines.push(line);
            lastNewLine = nextPos;
        } else {
            line = buffer.slice(lastNewLine);
            if (line.length) {
                lines.push(line);
            }
            break;
        }
    }

    return lines;
};

**Comment by ekeric13** [comment]
Implemented this within a PR:

https://github.com/nacholibre/node-readlines/pull/15
