### ISSUE TITLE
Close file?

### ISSUE THREAD

**Issue by huyanhh** [nacholibre/node-readlines#16]
Hi, thanks for the library. It seems like there was no manual close function. I tried to write it myself, but ended up with this error

```
fs.js:629
  return binding.close(fd);

TypeError: fd must be a file descriptor
```

Thought it would be as simple as

```
LineByLine.prototype.close = function() {
  fs.closeSync(this.fd);
  this.fd = null;
}
```

but it's not :(

Any pointers on how to go about this?

**Comment by nacholibre** [comment]
This means it's already closed, because I set `fd` to null when it's closed.

**Comment by huyanhh** [comment]
However, I get an error once I read around 23 files that I have too many files open. Somehow they're actually not closing.

**Comment by nacholibre** [comment]
Are you sure this is the problem? Only 23 files and you get too many open files? What OS are you using?

**Comment by huyanhh** [comment]
I'm unable to access the computer that I ran it on as of now, sorry. It was on High Sierra 10.13.3 nodejs 8.5. Now I'm running the same code on Sierra 10.12.6 nodejs 8.5 and it works fine. I can just close this until I can confidently replicate it.
