### ISSUE TITLE
Close fd after last read.

### ISSUE THREAD

**Issue by tracker1** [nacholibre/node-readlines#23]
https://github.com/nacholibre/node-readlines/blob/8682182a2ec776608d44c9917399114bca3ac1d2/readlines.js#L105

Seems like it would make sense to close the file after the last read... also, probably have a this.fd check inside the close method.

**Comment by smori1983** [comment]
In my project:
I might have to open many files synchronously.
To avoid file descriptor error, I have to close it every time.
For each file, when I find the target line, I stop to read the remaining lines.
But if I cannot find, LineByLine reaches to EOF and automatically closes.
I implement LineByLine.close() call in one place, so I need to check LineByLine.fd is number or not.

It might break the compatibility,
but it is convenient that `this.fd` is checked before `fs.closeSync(this.fd)`.
Is there any other side effects by doing this ?

**Comment by nacholibre** [comment]
@tracker1 
The file descriptor is closed after the last read.
https://github.com/nacholibre/node-readlines/blob/master/readlines.js#L147

@smori1983 
In your use case, when you find the line you need, you can close the file descriptor by calling `readlines.close()`. Does that work for you?
