### ISSUE TITLE
sleep x ms for every line use promise

### ISSUE THREAD

**Issue by dcaizued** [nacholibre/node-readlines#28]
is there is a way to read file and sleep  or pause like below

```
const sleep = (ms) => {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

const liner = new lineByLine('../lists/randomEmails.txt');
let line;
let lineNumber = 0;

while (line = liner.next()) {
    sleep(2000).then(()=>{
        console.log('Line ' + lineNumber + ': ' + line.toString());
        lineNumber++;
    })
}

console.log('end of line reached');
```

**Comment by nacholibre** [comment]
`liner.next()` is sync function, your `sleep` function is async, in your example the loop will not stop until finished, your `sleep` only slows the output with 2 seconds, but it doesn't actually sleep between the iteration.

you can try something like this
```
const liner = new lineByLine('../lists/randomEmails.txt');

setInterval(function () {
    console.log(liner.next());
}, 2000);
```

**Comment by smartdev10** [comment]
![image](https://user-images.githubusercontent.com/57545929/77859152-a78f3180-71ff-11ea-8fc4-66f8d23512f5.png)

**Comment by nacholibre** [comment]
If `liner.next()` is false, this means the end of file is reached.

**Comment by smartdev10** [comment]
the porblem is that the file has 45 emails not 23 , it doesn't read the whole file

**Comment by jsProj** [comment]
You're running liner.next 2 times which gets 2 lines per interval
