### ISSUE TITLE
Bug when the file has an empty line

### ISSUE THREAD

**Issue by jmjuanes** [nacholibre/node-readlines#3]
For example, if my file `test.txt` has five lines, but the third line has an empty line: 
```
This is the line 1 of my file.
This is the line 2 of my file.

This is the line 4 of my file.
This is the line 5 of my file.
``` 

When I run the next script:

```javascript
var lineByLine = require('n-readlines');
var liner = new lineByLine('./test.txt');

var line;
var counter = 1;

while (line = liner.next())
{
    console.log('>Iteration ' + counter); 
    console.log(line.toString('utf8')); 
    counter = counter + 1; 
} 
```

I expect that the script prints 5 iterations, but it prints in console the following output:

``` 
>Iteration 1
This is the line 1 of my file.
>Iteration 2
This is the line 2 of my file.
>Iteration 3

This is the line 4 of my file.
This is the line 5 of my file.
``` 

It seems that your script doesn't catch the empty lines... The content of the line on the iteration 3 is `'\nThis is the line 4 of my file.\nThis is the line 5 of my file.\n'`.

Thanks!

**Comment by alejvpro** [comment]
Same issue for me

**Comment by nacholibre** [comment]
I am not able to reproduce this bug, I've tried with this file:

https://github.com/nacholibre/node-readlines/blob/master/dummy_files/withEmptyLines.txt

and it works as expected. Can you please upload the file somewhere. Thanks.

**Comment by jmjuanes** [comment]
Hi @nacholibre 

It's true, the code that you have in this repo works well. As @alejvpro said, the problem is with the version `0.2.2` in NPM. I have checked it and is not the same that you have at this moment on your repo. In fact, the code that you have actually in your repo matches with the version `0.2.1` in NPM and it works perfect. I don't understand why you published a newest version in NPM but you kept the older version in GitHub...

My suggestion: I think that you must update the code in NPM, because the latest version published doesn't work with empty lines. For example, you can publish a new version called `0.2.3` with the code that you have actually in your git repository. You don't need to do anything more, and this will fix the problem.

Regards!

**Comment by nacholibre** [comment]
Ohh, I see. I've created new version 0.2.3 and I've pushed here and published in NPM.

thank you guys for your feedback.
