### ISSUE TITLE
no lines are found if there is no newline character in file

### ISSUE THREAD

**Issue by Wojtziech** [nacholibre/node-readlines#8]
When using example code on `textFile.txt` containing `abc` and nothing more (size of this file is exactly 3 bytes) first call of `next` can return `false` without returning first (andy only) line. I've tested it with node 6.9.2 on Ubuntu 12.04 (`false` always returned) and node 4.4.3 on Windows 8.1 32bit (randomly - `false` only or correct result).

**Comment by nacholibre** [comment]
It's fixed in the new version. Thank you for your feedback.
